spring:
  application:
    name: Room Management System
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/rms
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/RoomManagementSystem/protocol/openid-connect/certs
logging:
  level:
    org.springframework.security.oauth2: DEBUG